CreativityEdu/Controllers/EmployessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CreativityEdu.Data;
using CreativityEdu.Models;
using CreativityEdu.VM;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CreativityEdu.Controllers
{
    public class EmployessController : Controller
    {
        private CreativityEduContext _CreativityEduContext;
        private UserManager<AppUser> _userManager;
        public EmployessController(CreativityEduContext creativityEduContext, UserManager<AppUser> userManager)
        {
            _CreativityEduContext = creativityEduContext;
            _userManager = userManager;
        }





        public IActionResult Index()
        {
            var listEmployees = _CreativityEduContext.Employess.Include(x => x.User).Where(x => x.IsDelete == false).ToList();
            return View(listEmployees);
        }




        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeCreateVm empolyee)
        {
            var newUser = new AppUser
            {
                FirstName = empolyee.FirstName,
                LastName = empolyee.LastName,
                Email = empolyee.Email,
                Gender = empolyee.Gender,
                Address = empolyee.Address, 
                PhoneNumber = empolyee.PhoneNumber,
                UserName = empolyee.Email,
            };
            var result = await _userManager.CreateAsync(newUser, empolyee.Password);


            var newEmployee = new Employess
            {
                Sallary = empolyee.Salary,
                Department = empolyee.Departmant,
                UserId = newUser.Id
            };
            await _CreativityEduContext.Employess.AddAsync(newEmployee);
            await _CreativityEduContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //EDIT EMPLOYEE
        public IActionResult Edit(long id)
        {
            //search employee in db  by id 
            var employee = _CreativityEduContext.Employess.Include(x => x.User).FirstOrDefault(x => x.Id == id);

            //mapping data from employee class to createemolyeevm class 
            var updatEmployee = new EmployeeCreateVm()
            {

                Id = employee.Id,
                FirstName = employee.User.FirstName,
                LastName = employee.User.LastName,
                Email = employee.User.Email,
                Db = employee.User.DateOfBirthDate,
                Departmant = employee.Department,
                PhoneNumber = employee.User.PhoneNumber,
                Salary = employee.Sallary
            };
            return View("Edit", updatEmployee);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeCreateVm employee)
        {
            //search employee in db by id 
            var editEmployee = await _CreativityEduContext.Employess.FirstOrDefaultAsync(x => x.Id == employee.Id);
            editEmployee.Department = employee.Departmant;
            await _CreativityEduContext.SaveChangesAsync();

            var userDb = await _userManager.FindByIdAsync(editEmployee.UserId);
            userDb.FirstName = employee.FirstName;
            userDb.LastName = employee.LastName;
            userDb.PhoneNumber = employee.PhoneNumber;
            userDb.Email = employee.Email;
            userDb.UserName = employee.Email;

            await _userManager.UpdateAsync(userDb);
            await _CreativityEduContext.SaveChangesAsync();

            return RedirectToAction("index");
        }


        public IActionResult Delete(long id)
        {
            var employee = _CreativityEduContext.Employess.FirstOrDefault(x => x.Id == id);
            employee.IsDelete = true;
            _CreativityEduContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CreativityEdu/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CreativityEdu.Data;
using CreativityEdu.Models;
using CreativityEdu.VM;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CreativityEdu.Controllers
{
    public class StudentController : Controller
    {


        private CreativityEduContext _creativityEduContext;
        private UserManager<AppUser> _userManager;

        public StudentController(CreativityEduContext dbContext, UserManager<AppUser> userManager)
        {
            _userManager = userManager;
            _creativityEduContext = dbContext;
        }

        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentVm student)
        {

            var user = new AppUser
            {
                FirstName = student.FirstName,
                LastName = student.LastName,
                PhoneNumber = student.PhoneNumber,
                Email = student.Email,
                UserName = student.Email
            };
            var newUser = await _userManager.CreateAsync(user, student.Password);



            var newStudent = new Student
            {
                Nationality = student.Nationlaity,
                Status = Enums.StudentStatus.On,
                User = user
                //UserId = user.Id
            };
            await _creativityEduContext.Students.AddAsync(newStudent);
            await _creativityEduContext.SaveChangesAsync();

            return RedirectToAction("index");
        }


        public IActionResult Index()
        {
            var allStudent = _creativityEduContext.Students.Where(x => x.IsDelete == false).Include(x => x.User).ToList();
            return View(allStudent);
        }

        public IActionResult Edit(long id)
        {
            //search student in db  by id 
            var student = _creativityEduContext.Students.Include(x => x.User).FirstOrDefault(x => x.Id == id);


            var updateStudent = new CreateStudentVm
            {

                Id = student.Id,
                FirstName = student.User.FirstName,
                LastName = student.User.LastName,
                Email = student.User.Email,
                Db = student.User.DateOfBirthDate,
                Nationlaity = student.Nationality,
                PhoneNumber = student.User.PhoneNumber
            };



            return View("Edit", updateStudent);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(CreateStudentVm student)
        {
            //search student in db by id 
            var editStudent = await _creativityEduContext.Students.FirstOrDefaultAsync(x => x.Id == student.Id);
            editStudent.Nationality = student.Nationlaity;
            await _creativityEduContext.SaveChangesAsync();

            var userDb = await _userManager.FindByIdAsync(editStudent.UserId);
            userDb.FirstName = student.FirstName;
            userDb.LastName = student.LastName;
            userDb.PhoneNumber = student.PhoneNumber;
            userDb.Email = student.Email;
            userDb.UserName = student.Email;

            await _userManager.UpdateAsync(userDb);
            await _creativityEduContext.SaveChangesAsync();

            return RedirectToAction("index");
        }





        


        public IActionResult Delete(long id)
        {
            var student = _creativityEduContext.Students.FirstOrDefault(x => x.Id == id);
            student.IsDelete = true;
            _creativityEduContext.SaveChanges();


            return RedirectToAction("Index");
        }





    }
}

CreativityEdu/Views/Shared/_Header.cshtml
<!-- Logo Header -->
<div class="main-header" data-background-color="purple">

    <div class="logo-header">

        <a href="index.html" class="logo">
            <img src="~/assets/img/creativity.png" alt="navbar brand" class="navbar-brand"/>
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="fa fa-bars"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="fa fa-ellipsis-v"></i></button>
        <div class="navbar-minimize">
            <button class="btn btn-minimize btn-rounded">
                <i class="fa fa-bars"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->
    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg">

        <div class="container-fluid">
            <div class="collapse" id="search-nav">
                <form class="navbar-left navbar-form nav-search mr-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button type="submit" class="btn btn-search pr-1">
                                <i class="fa fa-search search-icon"></i>
                            </button>
                        </div>
                        <input type="text" placeholder="Search ..." class="form-control">
                    </div>
                </form>
            </div>
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                <li class="nav-item toggle-nav-search hidden-caret">
                    <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
                        <i class="fa fa-search"></i>
                    </a>
                </li>
                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link dropdown-toggle" href="#" id="messageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                    </a>
                    <ul class="dropdown-menu messages-notif-box animated fadeIn" aria-labelledby="messageDropdown">
                        <li>
                            <div class="dropdown-title d-flex justify-content-between align-items-center">
                                Messages
                                <a href="#" class="small">Mark all as read</a>
                            </div>
                        </li>
                        <li>
                            <div class="message-notif-scroll scrollbar-outer">
                                <div class="notif-center">
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="~/assets/img/jm_denis.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">Jimmy Denis</span>
                                            <span class="block">
                                                How are you ?
                                            </span>
                                            <span class="time">5 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="~/assets/img/chadengle.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">Chad</span>
                                            <span class="block">
                                                Ok, Thanks !
                                            </span>
                                            <span class="time">12 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="~/assets/img/mlane.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">Jhon Doe</span>
                                            <span class="block">
                                                Ready for the meeting today...
                                            </span>
                                            <span class="time">12 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="~/assets/img/talha.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="subject">Talha</span>
                                            <span class="block">
                                                Hi, Apa Kabar ?
                                            </span>
                                            <span class="time">17 minutes ago</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a class="see-all" href="javascript:void(0);">See all messages<i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item dropdown hidden-caret">
                    <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="notification">4</span>
                    </a>
                    <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
                        <li>
                            <div class="dropdown-title">You have 4 new notification</div>
                        </li>
                        <li>
                            <div class="notif-scroll scrollbar-outer">
                                <div class="notif-center">
                                    <a href="#">
                                        <div class="notif-icon notif-primary"> <i class="fa fa-user-plus"></i> </div>
                                        <div class="notif-content">
                                            <span class="block">
                                                New user registered
                                            </span>
                                            <span class="time">5 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-icon notif-success"> <i class="fa fa-comment"></i> </div>
                                        <div class="notif-content">
                                            <span class="block">
                                                Rahmad commented on Admin
                                            </span>
                                            <span class="time">12 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-img">
                                            <img src="~/assets/img/profile2.jpg" alt="Img Profile">
                                        </div>
                                        <div class="notif-content">
                                            <span class="block">
                                                Reza send messages to you
                                            </span>
                                            <span class="time">12 minutes ago</span>
                                        </div>
                                    </a>
                                    <a href="#">
                                        <div class="notif-icon notif-danger"> <i class="fa fa-heart"></i> </div>
                                        <div class="notif-content">
                                            <span class="block">
                                                Farrah liked Admin
                                            </span>
                                            <span class="time">17 minutes ago</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a class="see-all" href="javascript:void(0);">See all notifications<i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown hidden-caret">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm">
                            <img src="~/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <li>
                            <div class="user-box">
                                <div class="avatar-lg"><img src="~/assets/img/profile.jpg" alt="image profile" class="avatar-img rounded"></div>
                                <div class="u-text">
                                    <h4>Hizrian</h4>
                                    <p class="text-muted">hello@example.com</p><a href="profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">My Profile</a>
                            <a class="dropdown-item" href="#">My Balance</a>
                            <a class="dropdown-item" href="#">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Account Setting</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Logout</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>

</div>
<!-- End Navbar -->

CreativityEdu/Views/Shared/_SideBar.cshtml
<div class="sidebar-wrapper scrollbar-inner">
    <div class="sidebar-content">
        <div class="user">
            <div class="avatar-sm float-left mr-2">
                <img src="~/assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                    <span>
                        Creativity
                        <span class="user-level">Administrator</span>
                        <span class="caret"></span>
                    </span>
                </a>
                <div class="clearfix"></div>

                <div class="collapse in" id="collapseExample">
                    <ul class="nav">
                        <li>
                            <a href="#profile">
                                <span class="link-collapse">My Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#edit">
                                <span class="link-collapse">Edit Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#settings">
                                <span class="link-collapse">Settings</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a href="../index.html">
                    <a href="@Url.Action("Index","Home")" > <i class="fas fa-home"></i>
                    <p>Dashboard</p></a> 
                </a>
            </li>

            <li class="nav-item active submenu">
                <a data-toggle="collapse" href="#base">
                    <i class="fas fa-layer-group"></i>
                    <p>Student Dashboard</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse show" id="base">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","Student")">
                                <span class="sub-item">View Student</span>
                            </a>
                        </li>
                        <li>
                            <a href=".@Url.Action("Create","Student")">
                                <span class="sub-item">Create Student</span>
                            </a>
                        </li>
                        


                    </ul>
                </div>
            </li>
            <li class="nav-item active submenu">
                <a data-toggle="collapse" href="#forms">
                    <i class="fas fa-pen-square"></i>
                    <p>Employee Dashboard</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="forms">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","Employess")">
                                <span class="sub-item">View Employee</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create","Employess")">
                                <span class="sub-item">Create Employee</span>
                            </a>
                        </li>
                        <li>
                            
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item active submenu">
                <a data-toggle="collapse" href="#forms">
                    <i class="fas fa-pen-square"></i>
                    <p>Course Dashboard</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="forms">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","Employess")">
                                <span class="sub-item">View Course</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create","Employess")">
                                <span class="sub-item">Create Course</span>
                            </a>
                        </li>
                       
                    </ul>
                </div>
            </li>
            <li class="nav-item active submenu">
                <a data-toggle="collapse" href="#forms">
                    <i class="fas fa-pen-square"></i>
                    <p>Teacher Dashboard</p>
                    <span class="caret"></span>
                </a>
                <div class="collapse" id="forms">
                    <ul class="nav nav-collapse">
                        <li>
                            <a href="@Url.Action("Index","Employess")">
                                <span class="sub-item">View Teacher</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create","Employess")">
                                <span class="sub-item">Create Teacher</span>
                            </a>
                        </li>
                       
                    </ul>
                </div>
            </li>

        </ul>
    </div>
</div>